### ISSUE TITLE
Not Working after latest nextjs-auth0 lib update

### ISSUE THREAD

**Issue by bathan** [sir-dunxalot/cypress-nextjs-auth0#16]
Hi there, I was using this plugin on my NextJS project and after updating nextjs-auth0 to its latest version this stopped working. I believe it has something to do with the way cookies are being stored.

**Comment by foogunlana** [comment]
Which version of `nextjs-auth0`? It might be that you are using the default session cookie name in this project "a0:session", but the default session cookie name has changed in the `nextjs-auth0` project to `appSession`

**Comment by bathan** [comment]
Hello! So the issue I'm having is solved by this PR https://github.com/sir-dunxalot/cypress-nextjs-auth0/pull/14 

I tried the cookie name issue but its more complicated than that :)

**Comment by sir-dunxalot** [comment]
Yes, this will be solved when #14 is merged and released.

**Comment by mikestopcontinues** [comment]
Hey, any ETA on that merge?

**Comment by sir-dunxalot** [comment]
@mikestopcontinues Yes, #14 has code changes requested. Once the contributor has updated the PR, per review comments, the PR will be merged and released as a major version. I expect this will happen this week but it depends when the PR is updated.

**Comment by mikestopcontinues** [comment]
Thanks @sir-dunxalot. I appreciate it :)

**Comment by sir-dunxalot** [comment]
Fixed by #14.
