### ISSUE TITLE
Your page did not fire its load event within 2000ms

### ISSUE THREAD

**Issue by softshipper** [sir-dunxalot/cypress-nextjs-auth0#19]
Hi all 
Many times I have got the following error message:

![Screenshot from 2021-05-06 23-06-59](https://user-images.githubusercontent.com/56756949/117365611-d6c2a880-aebf-11eb-83a9-884be0d4742d.png)

What am I doing wrong? 

Thanks

**Comment by softshipper** [comment]
Somehow the load event does not get fired:
![Screenshot from 2021-05-07 17-07-32](https://user-images.githubusercontent.com/56756949/117470300-f0fb9580-af56-11eb-9f5f-6ed886256e50.png)

As you can see on the picture right on top the browser tries to load the page even though the page is fully loaded.

**Comment by softshipper** [comment]
I have figured out the problem because the logo can not be loaded:
![Screenshot from 2021-05-07 20-46-15](https://user-images.githubusercontent.com/56756949/117495121-83129680-af75-11eb-809b-e15938dcfd29.png)

as you can see in the picture on the bottom line.  That is the explanation, why the load event does not get triggered. 
Has anyone an idea of how to solve the problem?

**Comment by JustCallMeChris** [comment]
@softshipper did you solve your problem? How did you do that?
