### ISSUE TITLE
Where do I find auth0CookieSecret? 

### ISSUE THREAD

**Issue by simonwjackson** [sir-dunxalot/cypress-nextjs-auth0#20]
Is `auth0CookieSecret` created by auth0? Or do we generate this key ourselves?

**Comment by luisrudge** [comment]
I believe it has to be the same value as the `AUTH0_SECRET` set in https://github.com/auth0/nextjs-auth0/#basic-setup

**Comment by natterstefan** [comment]
Hi @simonwjackson, hi @luisrudge,

exactly it's the `AUTH0_SECRET` as used and illustrated here: https://github.com/sir-dunxalot/cypress-nextjs-auth0/blob/8ee2d609c28d1cad1dce9b4b802d22840b18e91a/cypress/plugins/index.js#L17.
