### ISSUE TITLE
The user does not have an active session or is not authenticated

### ISSUE THREAD

**Issue by tcetin** [sir-dunxalot/cypress-nextjs-auth0#31]
I am getting this error on cypress after cookie set.

I tried many times but I couldnt pass this error.

I did everything correctly with documentation.

![image](https://user-images.githubusercontent.com/5071753/140656964-4604ed62-b516-49a6-936c-202aced08530.png)

I think it is about setting session cookie.

After I looked in Application cookie. It didnt set this cookie.

![image](https://user-images.githubusercontent.com/5071753/140657665-e713135e-aad4-4dd3-9303-ede2f095c980.png)

**Comment by natterstefan** [comment]
Hi @tcetin,

I have a similar issue. Were you ever able to resolve it?

Thanks for your help.
