### ISSUE TITLE
cy.setCookie() had an unexpected error setting the requested cookie in Chrome.

### ISSUE THREAD

**Issue by dqunbp** [sir-dunxalot/cypress-nextjs-auth0#32]
After installing the latest version according to the instructions, when trying to call cy.login(), it throws an error
![image](https://user-images.githubusercontent.com/14041229/143587058-db5cf5b2-0d98-4127-9718-a57b7d234cf4.png)

```
"next": "^11.0.1",
"@auth0/nextjs-auth0": "^1.6.1",
"cypress": "^9.1.0",
"cypress-nextjs-auth0": "^2.0.1",
```

**Comment by rkrauskopf** [comment]
@dqunbp I'm seeing this error in chrome specifically as well. Firefox works just fine.

**Comment by richbachman** [comment]
Any updates on a workaround? Or fix incoming?

**Comment by dogancana** [comment]
I have the same issue. I did some investigation and turns out, you cannot set long cookies in cypress. 

You can try the below block for easy reproduction of same error.
`      cy.setCookie(
        'appSession',
        Array.apply(null, { length: 5000 })
          .map(() => '1')
          .join('')
      )
`

I don't have a workaround yet.

**Comment by natterstefan** [comment]
Hi @dogancana,

thanks for making us aware of a potential solution. Were you able to resolve this in your projects with this idea?
